package com.noto.app.util

import android.content.Context
import com.noto.app.R
import com.noto.app.domain.model.*
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString

fun Release.toJson(): String = NotoDefaultJson.encodeToString(this)
fun String.toRelease(): Release = NotoDefaultJson.decodeFromString(this)

fun Release.Companion.Current(context: Context): Release {
    return Release_2_3_0(
        Release.Changelog(
            listOf(
                context.stringResource(R.string.release_2_3_0_new_languages),
                context.stringResource(R.string.release_2_3_0_reminder),
                context.stringResource(R.string.release_2_3_0_selection),
                context.stringResource(R.string.release_2_3_0_find_in_note),
                context.stringResource(R.string.release_2_3_0_archive),
                context.stringResource(R.string.release_2_3_0_sorting),
                context.stringResource(R.string.release_2_3_0_reading_mode),
                context.stringResource(R.string.release_2_3_0_whats_new),
                context.stringResource(R.string.release_2_3_0_report_issues),
                context.stringResource(R.string.release_2_3_0_quick_note),
                context.stringResource(R.string.release_2_3_0_bug_fixes),
            )
        )
    )
}

fun Release.Companion.Previous(context: Context): List<Release> {
    return listOf(
        Release_2_2_3(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_2_3),
                )
            )
        ),
        Release_2_2_2(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_2_2),
                )
            )
        ),
        Release_2_2_1(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_2_1_languages),
                    context.stringResource(R.string.release_2_2_1_design),
                    context.stringResource(R.string.release_2_2_1_undo_redo),
                    context.stringResource(R.string.release_2_2_1_filtered_view),
                    context.stringResource(R.string.release_2_2_1_quick_exit),
                    context.stringResource(R.string.release_2_2_1_quick_note_tile),
                    context.stringResource(R.string.release_2_2_1_system_app_language),
                )
            )
        ),
        Release_2_2_0(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_2_0_languages),
                    context.stringResource(R.string.release_2_2_0_multi_selection),
                    context.stringResource(R.string.release_2_2_0_reading_mode),
                    context.stringResource(R.string.release_2_2_0_settings),
                    context.stringResource(R.string.release_2_2_0_paging),
                    context.stringResource(R.string.release_2_2_0_app_speed),
                    context.stringResource(R.string.release_2_2_0_import_json),
                    context.stringResource(R.string.release_2_2_0_black_theme),
                    context.stringResource(R.string.release_2_2_0_bug_fixes),
                )
            )
        ),
        Release_2_1_6(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_6)
                )
            )
        ),
        Release_2_1_5(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_5)
                )
            )
        ),
        Release_2_1_4(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_4_shortcuts),
                    context.stringResource(R.string.release_2_1_4_labels),
                    context.stringResource(R.string.release_2_1_4_bug_fixes),
                )
            )
        ),
        Release_2_1_3(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_3)
                )
            )
        ),
        Release_2_1_2(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_2)
                )
            )
        ),
        Release_2_1_1(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_1)
                )
            )
        ),
        Release_2_1_0(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_1_0_undo_redo),
                    context.stringResource(R.string.release_2_1_0_labels),
                    context.stringResource(R.string.release_2_1_0_app_bars),
                    context.stringResource(R.string.release_2_1_0_menu),
                    context.stringResource(R.string.release_2_1_0_new_folder),
                    context.stringResource(R.string.release_2_1_0_grouping_order),
                    context.stringResource(R.string.release_2_1_0_drag_elevation),
                    context.stringResource(R.string.release_2_1_0_preview),
                    context.stringResource(R.string.release_2_1_0_dates),
                    context.stringResource(R.string.release_2_1_0_highlight),
                    context.stringResource(R.string.release_2_1_0_navigation),
                    context.stringResource(R.string.release_2_1_0_material_you),
                    context.stringResource(R.string.release_2_1_0_splash_screen),
                    context.stringResource(R.string.release_2_1_0_reading_mode),
                    context.stringResource(R.string.release_2_1_0_scroll_position),
                    context.stringResource(R.string.release_2_1_0_disable_animations),
                    context.stringResource(R.string.release_2_1_0_import_data),
                    context.stringResource(R.string.release_2_1_0_vault_crash),
                    context.stringResource(R.string.release_2_1_0_label_filtering),
                    context.stringResource(R.string.release_2_1_0_app_icon),
                    context.stringResource(R.string.release_2_1_0_change_app_icon),
                    context.stringResource(R.string.release_2_1_0_undo_redo_swipe),
                    context.stringResource(R.string.release_2_1_0_language),
                    context.stringResource(R.string.release_2_1_0_bug_fixes),
                )
            )
        ),
        Release_2_0_1(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_0_1)
                )
            )
        ),
        Release_2_0_0(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_2_0_0_new_look),
                    context.stringResource(R.string.release_2_0_0_folders),
                    context.stringResource(R.string.release_2_0_0_animations),
                    context.stringResource(R.string.release_2_0_0_nested_folders),
                    context.stringResource(R.string.release_2_0_0_swipe_folder),
                    context.stringResource(R.string.release_2_0_0_general),
                    context.stringResource(R.string.release_2_0_0_all_recent),
                    context.stringResource(R.string.release_2_0_0_highlight_search),
                    context.stringResource(R.string.release_2_0_0_collapsing_toolbar),
                    context.stringResource(R.string.release_2_0_0_language),
                    context.stringResource(R.string.release_2_0_0_swipe_bottom_app_bar),
                    context.stringResource(R.string.release_2_0_0_navigation),
                    context.stringResource(R.string.release_2_0_0_settings_main_folder),
                    context.stringResource(R.string.release_2_0_0_settings_toolbar),
                    context.stringResource(R.string.release_2_0_0_shortcuts),
                    context.stringResource(R.string.release_2_0_0_bug_fixes),
                )
            )
        ),
        Release_1_8_0(
            Release.Changelog(
                listOf(
                    context.stringResource(R.string.release_1_8_0_vault),
                    context.stringResource(R.string.release_1_8_0_vault_timeout),
                    context.stringResource(R.string.release_1_8_0_vault_bio),
                    context.stringResource(R.string.release_1_8_0_language),
                    context.stringResource(R.string.release_1_8_0_reddit),
                    context.stringResource(R.string.release_1_8_0_bug_fixes),
                )
            )
        ),
    )
}
